### ISSUE TITLE
EnergyBatteryV2 not working 

### ISSUE THREAD

**Issue by sirrrich** [Busch-Jaeger/node-free-at-home#11]
Hello, I have the problem that it is not possible to set values ​​for an EnergyBatteryV2 device.
The same applies to an EnergyInverterBatteryV2 device, as this only creates an EnergyBatteryV2 device internally.
I discovered that there are no PairingIds available via the REST API and it is therefore not possible to set values.
Everything works for all other energy devices.
Is this a bug in Free@Home or is the EnergyBatteryV2 device not fully implemented?
In energy management, an icon and various panels are displayed, but no values ​​can be set.
I am in the process of implementing an implementation for the Zendure Solarflow system and would also like to integrate the battery.

**Comment by StefanGuelland** [comment]
If you create a device like this:
```
const freeAtHome = new FreeAtHome();
const channel = await freeAtHome.createEnergyInverterV2Device("123inverter");
```
You should get a device in free@home with this ouput datapoints:

````
 "outputs": {
              "odp0000": {
                "pairingID": 1190,
                "value": "0"
              },
              "odp0001": {
                "pairingID": 1191,
                "value": "0"
              },
              "odp0002": {
                "pairingID": 1221,
                "value": "0"
              },
              "odp0003": {
                "pairingID": 1222,
                "value": "100"
              },
              "odp0004": {
                "pairingID": 1224,
                "value": "0"
              }
            },
````

I have tested this with firmware 3.2.4.
The energy management devices are under development and the interface should be considered as not stable at the moment.

**Comment by sirrrich** [comment]
Thank you for the feedback,

however, the problem occurs when setting up a inverter-battery device:

```ts
const freeAtHome = new FreeAtHome();
const channel = await freeAtHome.createEnergyInverterBatteryV2Device("123inverterbattery");
```

or battery device:

```ts
const freeAtHome = new FreeAtHome();
const channel = await freeAtHome.freeAtHome.createEnergyBatteryV2Device("123battery");
```

The output datapoints for the battery device is then empty:

```json
"outputs": {
            },
```

I am also running version 3.2.4.

**Comment by sirrrich** [comment]
I was able to solve the problem myself after intensive research.
To set values for an `EnergyInverterBatteryV2Device` or `EnergyBatteryV2Device`, it is necessary to specify additional capabilities:

setBatteryPower -> CAP_ENERGY_CURRENT_POWER
setSoc -> CAP_STATE_OF_CHARGE
setImportedEnergyToday/setExportedEnergyToday -> CAP_ENERGY_TODAY
setTotalEnergyImported/setTotalEnergyExported -> CAP_ENERGY_TOTAL

Then the output datapoints are also correctly set:

```json
"outputs": {
              "odp0000": {
                "pairingID": 1197,
                "value": "0.46"
              },
              "odp0001": {
                "pairingID": 1196,
                "value": "49"
              },
              "odp0002": {
                "pairingID": 1222,
                "value": "2000"
              },
              "odp0003": {
                "pairingID": 1223,
                "value": "0"
              },
              "odp0004": {
                "pairingID": 1224,
                "value": "0"
              },
              "odp0005": {
                "pairingID": 1225,
                "value": "0"
              }
            },
```

```ts
const freeAtHome = new FreeAtHome();
const channel = await freeAtHome.createEnergyInverterBatteryV2Device("123inverterbattery",
[Capabilities.CAP_STATE_OF_CHARGE,Capabilities.CAP_ENERGY_CURRENT_POWER,Capabilities.CAP_ENERGY_TOTAL,Capabilities.CAP_ENERGY_TODAY]);
```

This is also correctly displayed in the interface:

<div align="center">
    <img src="https://github.com/Busch-Jaeger/node-free-at-home/assets/25660656/108ee6be-27a7-417f-b1ac-c79c8b3f90ad" alt="Beispielbild" width="300">
</div>

The API or documentation could potentially be more transparent at this point.
